### PR TITLE
build: update liquid to 4.0.4

### PR DESCRIPTION
**Pull request by gradybarrett**
Ruby 3.2 removed the "tainted" interface, which liquid <=4.0.3
still uses. Liquid 4.0.4 removes references to this interface so that
it works with Ruby 3.2.

Closes https://github.com/github/pages-gem/issues/859.

### CODE REVIEW

**Comment by gradybarrett** [comment]
@parkr hopefully this PR wasn't presumptuous. 😄

**Review by parkr — APPROVED** [review]

**Comment by parkr** [comment]
Nope! I can't merge this though since I don't work at GitHub anymore. Perhaps @yoannchaudet can help! This patched version fixes compatibility with Ruby 3.2.

**Comment by adhibsyed** [comment]
Would be great to have this merged.

**Comment by keithrbennett** [comment]
This issue is blocking the use of Ruby 3.2 for Github Pages sites. Could someone with the authority to merge it please take a look at it? It's a simple one-line fix. I can corroborate that tests pass with this change.

**Comment by gradybarrett** [comment]
Updated the branch and fixed my gpg config.

**Comment by vhxs** [comment]
+1 please merge this in, I've had to explicitly point my blog towards this forked repo

**Comment by JonathanCopeland** [comment]
Can confirm this is still a problem, I'm receiving:
 Liquid Exception: undefined method `tainted?' for ...
 
 Any ETA on when this will be merged?

**Comment by yoannchaudet** [comment]
Surfacing that to the team, we will look at it shortly and make a round of update.

**Comment by parkr** [comment]
@yoannchaudet I'm making a bug patch release of Jekyll soon that allows y'all to also upgrade `i18n` and `tzinfo`, if you want to bundle this patch release into your round of updates: https://github.com/jekyll/jekyll/pull/9282

**Comment by surelynottrue** [comment]
Is there any solution in place for this? This error is not allowing me to push any changes to my Jekyll website :)

**Comment by JonathanCopeland** [comment]
Same

**Review by tsusdere — APPROVED** [review]

**Comment by JonathanCopeland** [comment]
Hey everyone, I'm probably missing something, but after running _bundle update github-pages_ I'm still getting the tainted error. Is there anything else that I need to do to serve my site locally?

**Comment by yoannchaudet** [comment]
The gem has not been fully propagated in the systems. It is being updated today.

**Comment by yoannchaudet** [comment]
We should be good now: https://pages.github.com/versions. Still updating our legacy build infra but build on Actions are already current.

**Comment by parkr** [comment]
Thank you so much, @yoannchaudet!

**Comment by JonathanCopeland** [comment]
Working 100%. Thank you very much @yoannchaudet
