### ISSUE TITLE
undefined method `delete!' for nil:NilClass (after upgrade to 136)

### ISSUE THREAD

**Issue by pkra** [github/pages-gem#441]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [X] The site generated by GitHub Pages
- [X] Building sites locally

### What did you do (e.g., steps to reproduce)

Updated github-pages (from 134 to 136) and ran `bundle exec jekyll s`

More precisely, at first, I could not reproduce the issue locally until I updated my local bundle -- which only bumped `github-pages` from 134 to 136 (and `minima` to 2.1.1 but it's not used).

### What did you expect to happen?

Nothing to break.

### What happened instead?

Jekyll throws the following error while building

      Liquid Exception: undefined method `delete!' for nil:NilClass in /_layouts/default.html

But `default.html` does not seem to call such a method.

### Additional information

* Link to the source repo (if applicable): https://github.com/mathjax/mathjax-website
* Link to travis build with same failure (which is used for testing, we let github build the page): https://travis-ci.org/mathjax/MathJax-website/builds/227843641?utm_source=email&utm_medium=notification

Thanks in advance for any pointers.

**Comment by pkra** [comment]
Looking through the commits, the SEO plugin seemed the likely candidate (which is only strange since I could've sworn it was not updated when I updated to github-pages 136).

Disabling the plugin fixed my build issues so I'll file a bug there. 

Sorry for the noise.
