### ISSUE TITLE
Jekyll not working with ruby 3.3.4 (error in logger.rb)

### ISSUE THREAD

**Issue by flodolo** [github/pages-gem#920]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

I ran `bundle update github-pages`, and `bundle exec jekyll serve` stopped working with an error on logger

```
/Users/user/.rubies/ruby-3.3.4/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/lib/jekyll/configuration.rb:157:in `config_files'
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/lib/jekyll.rb:113:in `configuration'
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/lib/jekyll/command.rb:43:in `configuration_from_options'
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:89:in `start'
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /Users/user/.gem/ruby/3.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/user/.gem/ruby/3.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/user/.gem/ruby/3.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/user/.gem/ruby/3.3.4/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/user/.gem/ruby/3.3.4/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/user/.gem/ruby/3.3.4/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
	from /Users/user/.gem/ruby/3.3.4/bin/jekyll:25:in `load'
	from /Users/user/.gem/ruby/3.3.4/bin/jekyll:25:in `<top (required)>'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /Users/user/.gem/ruby/3.3.4/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
	from /Users/user/.rubies/ruby-3.3.4/bin/bundle:25:in `load'
	from /Users/user/.rubies/ruby-3.3.4/bin/bundle:25:in `<main>'
```

I tried updating to ruby 3.3.4, no luck. From what I understand, this would be fixed by updating to a more recent version of Jekyll (3.9.4+).

### What did you expect to happen?

Local page to be generated.

### What happened instead?

Tracelog with error on `logger.rb`.

**Comment by flodolo** [comment]
I'm completely unfamiliar with Ruby, but I don't understand why [this file](https://github.com/github/pages-gem/blob/master/lib/github-pages/dependencies.rb#L10C7-L10C27) has `jekyll 3.9.5`, but when I run `bundle update github-pages` I still see `jekyll 3.9.3` listed.

**Comment by flodolo** [comment]
I had to manually update Gemfile to use gh-pages 231. I somehow expected this to be done by `bundle update github-pages`.
